CREATE DATABASE lms; --CREATING THE DATABASE NAMED LMS

DROP DATABASE lms; -- INCASE I WANT TO DROP IT

CREATE TABLE courses(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    level VARCHAR(20) DEFAULT 'Débutant',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
) --CREATING TABLE THAT CONVTAINES THE NESSECCARY COLUMS

ALTER TABLE courses DROP COLUMN created_at -- DELETING created_at TO TEST ALTER 

ALTER TABLE courses
ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD uupdated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- ADDING created_att AND updated_at TO TEST ADDING USING ULTER AND ALSO TO TEST WHO DOES TIMESTAMP WORKS WHEN UPDATING A COURSE

INSERT INTO courses(title, description, level)
VALUES('Express as you never seen it', 'experience how senior Backend Engineer code looks like', 'Avancé') -- INSERTING DATA TO THE COURSES TABLE WHILE OMITING ID, CREATED_AT, AND UPDATED_AT SINCE THEIR VALUES ARE AUTO GENERATED

CREATE TABLE sections(
    id INT AUTO_INCREMENT PRIMARY KEY,
	course_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    position INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT unique_section_position UNIQUE(course_id, position)
) -- CREATING SECTIONS TABLE WITH course_id AS A FOREIGN KEY THAT DELETS A CHILED WHEN THE PARENT IS GONE, ALSO ADDING A UNIQUE COURSE ID AND POSITION RELATION TO AVOID HAVING 2 SECTIONS AT THE SAME POSITION 